#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-/home/ma/AQUA-FE_WS}"
TAUS="${TAUS:-0 1 2 3}"
BUDGETS="${BUDGETS:-6 10 12}"
DATASETS="${DATASETS:-a06 h07 a09}"
TAG_PREFIX="${TAG_PREFIX:-c3tau_sidecar}"
OUT_NOTE="${OUT_NOTE:-$ROOT/logs/conformal_calibration/${TAG_PREFIX}_export_scan_20260615_runs.txt}"
C3_SIDECAR_CONFIG="${C3_SIDECAR_CONFIG:-$ROOT/uw_frontend/configs/experiments/c3_loftr_mirror_v31_timing_frontend.yaml}"
C3_INIT_LOFTR_SIDECAR_RESCUE="${C3_INIT_LOFTR_SIDECAR_RESCUE:-1}"
C3_INIT_LOFTR_SIDECAR_MAX_COUNT="${C3_INIT_LOFTR_SIDECAR_MAX_COUNT:-10}"
C3_LOW_PARALLAX_LEARNED_HOLDOFF_FRAMES="${C3_LOW_PARALLAX_LEARNED_HOLDOFF_FRAMES:-8}"
C3_LEARNED_EXPORT_ALLOW_EARLY_LOFTR_SUPPORT="${C3_LEARNED_EXPORT_ALLOW_EARLY_LOFTR_SUPPORT:-1}"
C3_LEARNED_EXPORT_LOFTR_SUPPORT_COOLDOWN_FRAMES="${C3_LEARNED_EXPORT_LOFTR_SUPPORT_COOLDOWN_FRAMES:-20}"
C3_VINS_SAFE_INIT_SIDECAR_SUPPORT_SELECTION="${C3_VINS_SAFE_INIT_SIDECAR_SUPPORT_SELECTION:-1}"
C3_VINS_SAFE_INIT_SIDECAR_SUPPORT_COUNT="${C3_VINS_SAFE_INIT_SIDECAR_SUPPORT_COUNT:-0}"
C3_VINS_SAFE_INIT_SIDECAR_CLASSICAL_QUALITY_FLOOR="${C3_VINS_SAFE_INIT_SIDECAR_CLASSICAL_QUALITY_FLOOR:-0.8}"

mkdir -p "$(dirname "$OUT_NOTE")"
: > "$OUT_NOTE"

run_a06() {
  local tau=$1
  local budget=$2
  local tag="${TAG_PREFIX}_nc${tau}_b${budget}_a06_2210_2460"
  echo "[$(date +%H:%M:%S)] export A06 tau=$tau budget=$budget"
  FRONTEND_CONFIG="$C3_SIDECAR_CONFIG" \
  PREPROCESS=adaptive_clahe \
  FORMAL_THREE_LAYER_EXPORT=1 \
  FORMAL_EXPORT_ALLOW_SPARSE_BACKBONE=1 \
  FORMAL_EXPORT_ADAPTIVE_MIRROR_FALLBACK=1 \
  FORMAL_EXPORT_LEGACY_LOFTR_RESCUE=1 \
  FORMAL_EXPORT_ALLOW_LOW_PARALLAX_SIDECARS="${FORMAL_EXPORT_ALLOW_LOW_PARALLAX_SIDECARS:-0}" \
  FORMAL_EXPORT_LOW_TEXTURE_ACTIVE_SIDECAR=1 \
  EXPORT_CLASSICAL_MIRROR_BACKBONE=1 \
  SEMIDENSE_FALLBACK_METHOD=loftr \
  PROCESS_SKIPPED_FRAMES=1 \
  FRAME_OFFSET=1 \
  MEASUREMENT_SELECTION=0 \
  BACKEND_QUALITY_MODE="${BACKEND_QUALITY_MODE:-vins_safe}" \
  BACKEND_QUALITY_FLOOR="${BACKEND_QUALITY_FLOOR:-none}" \
  BACKEND_QUALITY_ALPHA="${BACKEND_QUALITY_ALPHA:-0.65}" \
  VINS_SAFE_SOURCE_SELECTION=1 \
  VINS_SAFE_WARMUP_FRAMES="${VINS_SAFE_WARMUP_FRAMES:-20}" \
  VINS_SAFE_MAX_LEARNED="${VINS_SAFE_MAX_LEARNED:-24}" \
  VINS_SAFE_MAX_RECOVERED="${VINS_SAFE_MAX_RECOVERED:-16}" \
  VINS_SAFE_MIN_LEARNED_AGE="${VINS_SAFE_MIN_LEARNED_AGE:-3}" \
  VINS_SAFE_PRESERVE_CLASSICAL_BUDGET="${VINS_SAFE_PRESERVE_CLASSICAL_BUDGET:-0}" \
  INIT_PARALLAX_GATE=1 \
  INIT_PARALLAX_THRESHOLD_PX="${INIT_PARALLAX_THRESHOLD_PX:-7.0}" \
  VINS_SAFE_INIT_SIDECAR_SUPPORT_SELECTION="$C3_VINS_SAFE_INIT_SIDECAR_SUPPORT_SELECTION" \
  VINS_SAFE_INIT_SIDECAR_SUPPORT_COUNT="$C3_VINS_SAFE_INIT_SIDECAR_SUPPORT_COUNT" \
  VINS_SAFE_INIT_SIDECAR_CLASSICAL_QUALITY_FLOOR="$C3_VINS_SAFE_INIT_SIDECAR_CLASSICAL_QUALITY_FLOOR" \
  INIT_LOFTR_SIDECAR_RESCUE="${INIT_LOFTR_SIDECAR_RESCUE:-$C3_INIT_LOFTR_SIDECAR_RESCUE}" \
  INIT_LOFTR_SIDECAR_MAX_COUNT="${INIT_LOFTR_SIDECAR_MAX_COUNT:-$C3_INIT_LOFTR_SIDECAR_MAX_COUNT}" \
  LOW_PARALLAX_LEARNED_HOLDOFF_FRAMES="${LOW_PARALLAX_LEARNED_HOLDOFF_FRAMES:-$C3_LOW_PARALLAX_LEARNED_HOLDOFF_FRAMES}" \
  LEARNED_EXPORT_DEGRADATION_GATE=1 \
  LEARNED_EXPORT_MIN_CLASSICAL_TRACKS="${LEARNED_EXPORT_MIN_CLASSICAL_TRACKS:-300}" \
  LEARNED_EXPORT_MIN_CLASSICAL_GRID="${LEARNED_EXPORT_MIN_CLASSICAL_GRID:-0.84}" \
  LEARNED_EXPORT_MIN_AGE="${LEARNED_EXPORT_MIN_AGE:-5}" \
  LEARNED_EXPORT_MIN_QUALITY="${LEARNED_EXPORT_MIN_QUALITY:-0.20}" \
  LEARNED_EXPORT_MIN_NCC="${LEARNED_EXPORT_MIN_NCC:-0.58}" \
  LEARNED_EXPORT_MAX_FB="${LEARNED_EXPORT_MAX_FB:-0.90}" \
  LEARNED_EXPORT_LOFTR_MIN_QUALITY="${LEARNED_EXPORT_LOFTR_MIN_QUALITY:-0.05}" \
  LEARNED_EXPORT_LOFTR_MIN_NCC="${LEARNED_EXPORT_LOFTR_MIN_NCC:-0.40}" \
  LEARNED_EXPORT_LOFTR_MAX_FB="${LEARNED_EXPORT_LOFTR_MAX_FB:-1.20}" \
  LEARNED_EXPORT_BENEFIT_GATE=1 \
  LEARNED_EXPORT_MIN_GRID_GAIN="${LEARNED_EXPORT_MIN_GRID_GAIN:-0.041}" \
  LEARNED_EXPORT_MIN_NEW_CELLS="$tau" \
  LEARNED_EXPORT_MIN_NEW_CELL_RATIO="${LEARNED_EXPORT_MIN_NEW_CELL_RATIO:-0.30}" \
  LEARNED_EXPORT_MAX_PER_NEW_CELL="${LEARNED_EXPORT_MAX_PER_NEW_CELL:-1}" \
  LEARNED_EXPORT_SIDECAR_MAX_OBSERVATIONS="$budget" \
  LEARNED_EXPORT_LOFTR_PLANAR_RESCUE=1 \
  LEARNED_EXPORT_LOFTR_PLANAR_MAX_COUNT="${LEARNED_EXPORT_LOFTR_PLANAR_MAX_COUNT:-6}" \
  LEARNED_EXPORT_LOFTR_PLANAR_MIN_CLASSICAL_MOTION_PX="${LEARNED_EXPORT_LOFTR_PLANAR_MIN_CLASSICAL_MOTION_PX:-1.2}" \
  LEARNED_EXPORT_LOFTR_WEAK_CELL_RESCUE=1 \
  LEARNED_EXPORT_LOFTR_WEAK_CELL_MAX_COUNT="${LEARNED_EXPORT_LOFTR_WEAK_CELL_MAX_COUNT:-6}" \
  LEARNED_EXPORT_LOFTR_RESCUE_MAX_CLASSICAL_TRACKS="${LEARNED_EXPORT_LOFTR_RESCUE_MAX_CLASSICAL_TRACKS:-220}" \
  LEARNED_EXPORT_LOFTR_SUPPORT_MAX_INIT_PARALLAX_PX="${LEARNED_EXPORT_LOFTR_SUPPORT_MAX_INIT_PARALLAX_PX:-0}" \
  LEARNED_EXPORT_LOFTR_SUPPORT_MAX_CLASSICAL_MOTION_PX="${LEARNED_EXPORT_LOFTR_SUPPORT_MAX_CLASSICAL_MOTION_PX:-3.7}" \
  LEARNED_EXPORT_LOFTR_MIN_EXPORT_COUNT="${LEARNED_EXPORT_LOFTR_MIN_EXPORT_COUNT:-0}" \
  LEARNED_EXPORT_LOFTR_SUPPORT_COOLDOWN_FRAMES="${LEARNED_EXPORT_LOFTR_SUPPORT_COOLDOWN_FRAMES:-$C3_LEARNED_EXPORT_LOFTR_SUPPORT_COOLDOWN_FRAMES}" \
  LEARNED_EXPORT_ALLOW_EARLY_LOFTR_SUPPORT="${LEARNED_EXPORT_ALLOW_EARLY_LOFTR_SUPPORT:-$C3_LEARNED_EXPORT_ALLOW_EARLY_LOFTR_SUPPORT}" \
  LEARNED_EXPORT_GEOMETRY_GATE=1 \
  LEARNED_EXPORT_REQUIRE_CONFIRMED=1 \
  EXPORT_MAX_FEATURES=350 \
  FORCE_EXPORT=1 \
  RUN_VINS=0 \
  TAG="$tag" \
  bash "$ROOT/scripts/run_aqualoc_archaeo_vins_eval.sh" external 6 2210 2460 hybrid_superpoint_lightglue 2 \
    > "$ROOT/logs/conformal_calibration/${tag}.export.log" 2>&1
  echo "$ROOT/logs/aqualoc_archaeo_vins/external_hybrid_superpoint_lightglue_every2_${tag}" >> "$OUT_NOTE"
}

run_h07() {
  local tau=$1
  local budget=$2
  local tag="${TAG_PREFIX}_nc${tau}_b${budget}_h07_1660_1950"
  echo "[$(date +%H:%M:%S)] export H07 tau=$tau budget=$budget"
  FRONTEND_CONFIG="$C3_SIDECAR_CONFIG" \
  PREPROCESS=adaptive_clahe \
  FORMAL_THREE_LAYER_EXPORT=1 \
  FORMAL_EXPORT_ALLOW_SPARSE_BACKBONE=1 \
  FORMAL_EXPORT_ADAPTIVE_MIRROR_FALLBACK=1 \
  FORMAL_EXPORT_LEGACY_LOFTR_RESCUE=1 \
  FORMAL_EXPORT_ALLOW_LOW_PARALLAX_SIDECARS="${FORMAL_EXPORT_ALLOW_LOW_PARALLAX_SIDECARS:-0}" \
  FORMAL_EXPORT_LOW_TEXTURE_ACTIVE_SIDECAR=1 \
  EXPORT_CLASSICAL_MIRROR_BACKBONE=1 \
  SEMIDENSE_FALLBACK_METHOD=loftr \
  PROCESS_SKIPPED_FRAMES=1 \
  FRAME_OFFSET=1 \
  MEASUREMENT_SELECTION=0 \
  BACKEND_QUALITY_MODE="${BACKEND_QUALITY_MODE:-vins_safe}" \
  BACKEND_QUALITY_FLOOR="${BACKEND_QUALITY_FLOOR:-none}" \
  BACKEND_QUALITY_ALPHA="${BACKEND_QUALITY_ALPHA:-0.65}" \
  VINS_SAFE_SOURCE_SELECTION=1 \
  VINS_SAFE_WARMUP_FRAMES="${VINS_SAFE_WARMUP_FRAMES:-20}" \
  VINS_SAFE_MAX_LEARNED="${VINS_SAFE_MAX_LEARNED:-24}" \
  VINS_SAFE_MAX_RECOVERED="${VINS_SAFE_MAX_RECOVERED:-16}" \
  VINS_SAFE_MIN_LEARNED_AGE="${VINS_SAFE_MIN_LEARNED_AGE:-3}" \
  VINS_SAFE_PRESERVE_CLASSICAL_BUDGET="${VINS_SAFE_PRESERVE_CLASSICAL_BUDGET:-0}" \
  INIT_PARALLAX_GATE=1 \
  INIT_PARALLAX_THRESHOLD_PX="${INIT_PARALLAX_THRESHOLD_PX:-7.0}" \
  VINS_SAFE_INIT_SIDECAR_SUPPORT_SELECTION="$C3_VINS_SAFE_INIT_SIDECAR_SUPPORT_SELECTION" \
  VINS_SAFE_INIT_SIDECAR_SUPPORT_COUNT="$C3_VINS_SAFE_INIT_SIDECAR_SUPPORT_COUNT" \
  VINS_SAFE_INIT_SIDECAR_CLASSICAL_QUALITY_FLOOR="$C3_VINS_SAFE_INIT_SIDECAR_CLASSICAL_QUALITY_FLOOR" \
  INIT_LOFTR_SIDECAR_RESCUE="${INIT_LOFTR_SIDECAR_RESCUE:-$C3_INIT_LOFTR_SIDECAR_RESCUE}" \
  INIT_LOFTR_SIDECAR_MAX_COUNT="${INIT_LOFTR_SIDECAR_MAX_COUNT:-$C3_INIT_LOFTR_SIDECAR_MAX_COUNT}" \
  LOW_PARALLAX_LEARNED_HOLDOFF_FRAMES="${LOW_PARALLAX_LEARNED_HOLDOFF_FRAMES:-$C3_LOW_PARALLAX_LEARNED_HOLDOFF_FRAMES}" \
  LEARNED_EXPORT_DEGRADATION_GATE=1 \
  LEARNED_EXPORT_MIN_CLASSICAL_TRACKS="${LEARNED_EXPORT_MIN_CLASSICAL_TRACKS:-300}" \
  LEARNED_EXPORT_MIN_CLASSICAL_GRID="${LEARNED_EXPORT_MIN_CLASSICAL_GRID:-0.84}" \
  LEARNED_EXPORT_MIN_AGE="${LEARNED_EXPORT_MIN_AGE:-5}" \
  LEARNED_EXPORT_MIN_QUALITY="${LEARNED_EXPORT_MIN_QUALITY:-0.20}" \
  LEARNED_EXPORT_MIN_NCC="${LEARNED_EXPORT_MIN_NCC:-0.58}" \
  LEARNED_EXPORT_MAX_FB="${LEARNED_EXPORT_MAX_FB:-0.90}" \
  LEARNED_EXPORT_LOFTR_MIN_QUALITY="${LEARNED_EXPORT_LOFTR_MIN_QUALITY:-0.05}" \
  LEARNED_EXPORT_LOFTR_MIN_NCC="${LEARNED_EXPORT_LOFTR_MIN_NCC:-0.40}" \
  LEARNED_EXPORT_LOFTR_MAX_FB="${LEARNED_EXPORT_LOFTR_MAX_FB:-1.20}" \
  LEARNED_EXPORT_BENEFIT_GATE=1 \
  LEARNED_EXPORT_MIN_GRID_GAIN="${LEARNED_EXPORT_MIN_GRID_GAIN:-0.041}" \
  LEARNED_EXPORT_MIN_NEW_CELLS="$tau" \
  LEARNED_EXPORT_MIN_NEW_CELL_RATIO="${LEARNED_EXPORT_MIN_NEW_CELL_RATIO:-0.30}" \
  LEARNED_EXPORT_MAX_PER_NEW_CELL="${LEARNED_EXPORT_MAX_PER_NEW_CELL:-1}" \
  LEARNED_EXPORT_SIDECAR_MAX_OBSERVATIONS="$budget" \
  LEARNED_EXPORT_LOFTR_PLANAR_RESCUE=1 \
  LEARNED_EXPORT_LOFTR_PLANAR_MAX_COUNT="${LEARNED_EXPORT_LOFTR_PLANAR_MAX_COUNT:-6}" \
  LEARNED_EXPORT_LOFTR_PLANAR_MIN_CLASSICAL_MOTION_PX="${LEARNED_EXPORT_LOFTR_PLANAR_MIN_CLASSICAL_MOTION_PX:-1.2}" \
  LEARNED_EXPORT_LOFTR_WEAK_CELL_RESCUE=1 \
  LEARNED_EXPORT_LOFTR_WEAK_CELL_MAX_COUNT="${LEARNED_EXPORT_LOFTR_WEAK_CELL_MAX_COUNT:-6}" \
  LEARNED_EXPORT_LOFTR_RESCUE_MAX_CLASSICAL_TRACKS="${LEARNED_EXPORT_LOFTR_RESCUE_MAX_CLASSICAL_TRACKS:-220}" \
  LEARNED_EXPORT_LOFTR_SUPPORT_MAX_INIT_PARALLAX_PX="${LEARNED_EXPORT_LOFTR_SUPPORT_MAX_INIT_PARALLAX_PX:-0}" \
  LEARNED_EXPORT_LOFTR_SUPPORT_MAX_CLASSICAL_MOTION_PX="${LEARNED_EXPORT_LOFTR_SUPPORT_MAX_CLASSICAL_MOTION_PX:-3.7}" \
  LEARNED_EXPORT_LOFTR_MIN_EXPORT_COUNT="${LEARNED_EXPORT_LOFTR_MIN_EXPORT_COUNT:-0}" \
  LEARNED_EXPORT_LOFTR_SUPPORT_COOLDOWN_FRAMES="${LEARNED_EXPORT_LOFTR_SUPPORT_COOLDOWN_FRAMES:-$C3_LEARNED_EXPORT_LOFTR_SUPPORT_COOLDOWN_FRAMES}" \
  LEARNED_EXPORT_ALLOW_EARLY_LOFTR_SUPPORT="${LEARNED_EXPORT_ALLOW_EARLY_LOFTR_SUPPORT:-$C3_LEARNED_EXPORT_ALLOW_EARLY_LOFTR_SUPPORT}" \
  LEARNED_EXPORT_GEOMETRY_GATE=1 \
  LEARNED_EXPORT_REQUIRE_CONFIRMED=1 \
  EXPORT_MAX_FEATURES=350 \
  FORCE_EXPORT=1 \
  RUN_VINS=0 \
  TAG="$tag" \
  bash "$ROOT/scripts/run_aqualoc_real_vins_eval.sh" external 1660 1950 hybrid_superpoint_lightglue 2 \
    > "$ROOT/logs/conformal_calibration/${tag}.export.log" 2>&1
  echo "$ROOT/logs/aqualoc_real_vins/external_hybrid_superpoint_lightglue_every2_${tag}" >> "$OUT_NOTE"
}

run_a09() {
  local tau=$1
  local budget=$2
  local tag="${TAG_PREFIX}_nc${tau}_b${budget}_a09_5920_6060"
  echo "[$(date +%H:%M:%S)] export A09 tau=$tau budget=$budget"
  FRONTEND_CONFIG="$C3_SIDECAR_CONFIG" \
  PREPROCESS=adaptive_clahe \
  FORMAL_THREE_LAYER_EXPORT=1 \
  FORMAL_EXPORT_ALLOW_SPARSE_BACKBONE=1 \
  FORMAL_EXPORT_ADAPTIVE_MIRROR_FALLBACK=1 \
  FORMAL_EXPORT_LEGACY_LOFTR_RESCUE=1 \
  FORMAL_EXPORT_ALLOW_LOW_PARALLAX_SIDECARS="${FORMAL_EXPORT_ALLOW_LOW_PARALLAX_SIDECARS:-0}" \
  FORMAL_EXPORT_LOW_TEXTURE_ACTIVE_SIDECAR=1 \
  EXPORT_CLASSICAL_MIRROR_BACKBONE=1 \
  SEMIDENSE_FALLBACK_METHOD=loftr \
  PROCESS_SKIPPED_FRAMES=1 \
  FRAME_OFFSET=1 \
  MEASUREMENT_SELECTION=0 \
  BACKEND_QUALITY_MODE="${BACKEND_QUALITY_MODE:-vins_safe}" \
  BACKEND_QUALITY_FLOOR="${BACKEND_QUALITY_FLOOR:-none}" \
  BACKEND_QUALITY_ALPHA="${BACKEND_QUALITY_ALPHA:-0.65}" \
  VINS_SAFE_SOURCE_SELECTION=1 \
  VINS_SAFE_WARMUP_FRAMES="${VINS_SAFE_WARMUP_FRAMES:-20}" \
  VINS_SAFE_MAX_LEARNED="${VINS_SAFE_MAX_LEARNED:-24}" \
  VINS_SAFE_MAX_RECOVERED="${VINS_SAFE_MAX_RECOVERED:-16}" \
  VINS_SAFE_MIN_LEARNED_AGE="${VINS_SAFE_MIN_LEARNED_AGE:-3}" \
  VINS_SAFE_PRESERVE_CLASSICAL_BUDGET="${VINS_SAFE_PRESERVE_CLASSICAL_BUDGET:-0}" \
  INIT_PARALLAX_GATE=1 \
  INIT_PARALLAX_THRESHOLD_PX="${INIT_PARALLAX_THRESHOLD_PX:-7.0}" \
  VINS_SAFE_INIT_SIDECAR_SUPPORT_SELECTION="$C3_VINS_SAFE_INIT_SIDECAR_SUPPORT_SELECTION" \
  VINS_SAFE_INIT_SIDECAR_SUPPORT_COUNT="$C3_VINS_SAFE_INIT_SIDECAR_SUPPORT_COUNT" \
  VINS_SAFE_INIT_SIDECAR_CLASSICAL_QUALITY_FLOOR="$C3_VINS_SAFE_INIT_SIDECAR_CLASSICAL_QUALITY_FLOOR" \
  INIT_LOFTR_SIDECAR_RESCUE="${INIT_LOFTR_SIDECAR_RESCUE:-$C3_INIT_LOFTR_SIDECAR_RESCUE}" \
  INIT_LOFTR_SIDECAR_MAX_COUNT="${INIT_LOFTR_SIDECAR_MAX_COUNT:-$C3_INIT_LOFTR_SIDECAR_MAX_COUNT}" \
  LOW_PARALLAX_LEARNED_HOLDOFF_FRAMES="${LOW_PARALLAX_LEARNED_HOLDOFF_FRAMES:-$C3_LOW_PARALLAX_LEARNED_HOLDOFF_FRAMES}" \
  LEARNED_EXPORT_DEGRADATION_GATE=1 \
  LEARNED_EXPORT_MIN_CLASSICAL_TRACKS="${LEARNED_EXPORT_MIN_CLASSICAL_TRACKS:-300}" \
  LEARNED_EXPORT_MIN_CLASSICAL_GRID="${LEARNED_EXPORT_MIN_CLASSICAL_GRID:-0.84}" \
  LEARNED_EXPORT_MIN_AGE="${LEARNED_EXPORT_MIN_AGE:-5}" \
  LEARNED_EXPORT_MIN_QUALITY="${LEARNED_EXPORT_MIN_QUALITY:-0.20}" \
  LEARNED_EXPORT_MIN_NCC="${LEARNED_EXPORT_MIN_NCC:-0.58}" \
  LEARNED_EXPORT_MAX_FB="${LEARNED_EXPORT_MAX_FB:-0.90}" \
  LEARNED_EXPORT_LOFTR_MIN_QUALITY="${LEARNED_EXPORT_LOFTR_MIN_QUALITY:-0.05}" \
  LEARNED_EXPORT_LOFTR_MIN_NCC="${LEARNED_EXPORT_LOFTR_MIN_NCC:-0.40}" \
  LEARNED_EXPORT_LOFTR_MAX_FB="${LEARNED_EXPORT_LOFTR_MAX_FB:-1.20}" \
  LEARNED_EXPORT_BENEFIT_GATE=1 \
  LEARNED_EXPORT_MIN_GRID_GAIN="${LEARNED_EXPORT_MIN_GRID_GAIN:-0.041}" \
  LEARNED_EXPORT_MIN_NEW_CELLS="$tau" \
  LEARNED_EXPORT_MIN_NEW_CELL_RATIO="${LEARNED_EXPORT_MIN_NEW_CELL_RATIO:-0.30}" \
  LEARNED_EXPORT_MAX_PER_NEW_CELL="${LEARNED_EXPORT_MAX_PER_NEW_CELL:-1}" \
  LEARNED_EXPORT_SIDECAR_MAX_OBSERVATIONS="$budget" \
  LEARNED_EXPORT_LOFTR_PLANAR_RESCUE=1 \
  LEARNED_EXPORT_LOFTR_PLANAR_MAX_COUNT="${LEARNED_EXPORT_LOFTR_PLANAR_MAX_COUNT:-6}" \
  LEARNED_EXPORT_LOFTR_PLANAR_MIN_CLASSICAL_MOTION_PX="${LEARNED_EXPORT_LOFTR_PLANAR_MIN_CLASSICAL_MOTION_PX:-1.2}" \
  LEARNED_EXPORT_LOFTR_WEAK_CELL_RESCUE=1 \
  LEARNED_EXPORT_LOFTR_WEAK_CELL_MAX_COUNT="${LEARNED_EXPORT_LOFTR_WEAK_CELL_MAX_COUNT:-6}" \
  LEARNED_EXPORT_LOFTR_RESCUE_MAX_CLASSICAL_TRACKS="${LEARNED_EXPORT_LOFTR_RESCUE_MAX_CLASSICAL_TRACKS:-220}" \
  LEARNED_EXPORT_LOFTR_SUPPORT_MAX_INIT_PARALLAX_PX="${LEARNED_EXPORT_LOFTR_SUPPORT_MAX_INIT_PARALLAX_PX:-0}" \
  LEARNED_EXPORT_LOFTR_SUPPORT_MAX_CLASSICAL_MOTION_PX="${LEARNED_EXPORT_LOFTR_SUPPORT_MAX_CLASSICAL_MOTION_PX:-3.7}" \
  LEARNED_EXPORT_LOFTR_MIN_EXPORT_COUNT="${LEARNED_EXPORT_LOFTR_MIN_EXPORT_COUNT:-0}" \
  LEARNED_EXPORT_LOFTR_SUPPORT_COOLDOWN_FRAMES="${LEARNED_EXPORT_LOFTR_SUPPORT_COOLDOWN_FRAMES:-$C3_LEARNED_EXPORT_LOFTR_SUPPORT_COOLDOWN_FRAMES}" \
  LEARNED_EXPORT_ALLOW_EARLY_LOFTR_SUPPORT="${LEARNED_EXPORT_ALLOW_EARLY_LOFTR_SUPPORT:-$C3_LEARNED_EXPORT_ALLOW_EARLY_LOFTR_SUPPORT}" \
  LEARNED_EXPORT_GEOMETRY_GATE=1 \
  LEARNED_EXPORT_REQUIRE_CONFIRMED=1 \
  EXPORT_MAX_FEATURES=350 \
  FORCE_EXPORT=1 \
  RUN_VINS=0 \
  TAG="$tag" \
  bash "$ROOT/scripts/run_aqualoc_archaeo_vins_eval.sh" external 9 5920 6060 hybrid_superpoint_lightglue 2 \
    > "$ROOT/logs/conformal_calibration/${tag}.export.log" 2>&1
  echo "$ROOT/logs/aqualoc_archaeo_vins/external_hybrid_superpoint_lightglue_every2_${tag}" >> "$OUT_NOTE"
}

for dataset in $DATASETS; do
  case "$dataset" in
    a06)
      for tau in $TAUS; do
        for budget in $BUDGETS; do
          run_a06 "$tau" "$budget"
        done
      done
      ;;
    h07)
      for tau in $TAUS; do
        for budget in $BUDGETS; do
          run_h07 "$tau" "$budget"
        done
      done
      ;;
    a09)
      for tau in $TAUS; do
        for budget in $BUDGETS; do
          run_a09 "$tau" "$budget"
        done
      done
      ;;
    *)
      echo "unknown dataset '$dataset' in DATASETS='$DATASETS'" >&2
      exit 2
      ;;
  esac
done

echo "[$(date +%H:%M:%S)] C3 tau export scan done"
echo "run_list=$OUT_NOTE"
