#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-/home/ma/AQUA-FE_WS}"
cd "$ROOT"

WINDOWS="${WINDOWS:-h07_normal a06_lowtexture a08_lowtexture}"
RUN_BASELINE="${RUN_BASELINE:-1}"
RUN_PROTECTED_BASELINE="${RUN_PROTECTED_BASELINE:-1}"
RUN_PROPOSED="${RUN_PROPOSED:-1}"
FORCE_EXPORT="${FORCE_EXPORT:-1}"
EVERY_N="${EVERY_N:-2}"
VALIDATION_TAG_PREFIX="${VALIDATION_TAG_PREFIX:-slamgate_v1}"
PROPOSED_BENEFIT_ALL_SOURCES="${PROPOSED_BENEFIT_ALL_SOURCES:-0}"
PROPOSED_MATURE_CELL_RESCUE="${PROPOSED_MATURE_CELL_RESCUE:-0}"
BASELINE_EXPORT_MAX_FEATURES="${BASELINE_EXPORT_MAX_FEATURES:-350}"
PROTECTED_EXPORT_MAX_FEATURES="${PROTECTED_EXPORT_MAX_FEATURES:-350}"
PROPOSED_EXPORT_MAX_FEATURES="${PROPOSED_EXPORT_MAX_FEATURES:-350}"
PROPOSED_BACKEND_LOFTR_QUALITY_SCALE="${PROPOSED_BACKEND_LOFTR_QUALITY_SCALE:-0.60}"
PROTECTED_BACKEND_QUALITY_FLOOR="${PROTECTED_BACKEND_QUALITY_FLOOR:-none}"
PROPOSED_BACKEND_QUALITY_FLOOR="${PROPOSED_BACKEND_QUALITY_FLOOR:-none}"
PROPOSED_VINS_SAFE_MAX_TOTAL="${PROPOSED_VINS_SAFE_MAX_TOTAL:-${VINS_SAFE_MAX_TOTAL:-}}"
PROPOSED_VINS_SAFE_MAX_LEARNED="${PROPOSED_VINS_SAFE_MAX_LEARNED:-${VINS_SAFE_MAX_LEARNED:-24}}"
PROPOSED_INIT_LOFTR_SIDECAR_RESCUE="${PROPOSED_INIT_LOFTR_SIDECAR_RESCUE:-${INIT_LOFTR_SIDECAR_RESCUE:-0}}"
PROPOSED_LEARNED_MIN_CLASSICAL_GRID="${PROPOSED_LEARNED_MIN_CLASSICAL_GRID:-${LEARNED_EXPORT_MIN_CLASSICAL_GRID:-0.84}}"
PROPOSED_LEARNED_MIN_CLASSICAL_TRACKS="${PROPOSED_LEARNED_MIN_CLASSICAL_TRACKS:-${LEARNED_EXPORT_MIN_CLASSICAL_TRACKS:-300}}"
PROPOSED_LEARNED_MIN_AGE="${PROPOSED_LEARNED_MIN_AGE:-${LEARNED_EXPORT_MIN_AGE:-5}}"
PROPOSED_LEARNED_MIN_NCC="${PROPOSED_LEARNED_MIN_NCC:-${LEARNED_EXPORT_MIN_NCC:-0.58}}"
PROPOSED_LEARNED_MAX_FB="${PROPOSED_LEARNED_MAX_FB:-${LEARNED_EXPORT_MAX_FB:-0.90}}"
PROPOSED_LEARNED_LOFTR_MIN_QUALITY="${PROPOSED_LEARNED_LOFTR_MIN_QUALITY:-${LEARNED_EXPORT_LOFTR_MIN_QUALITY:-}}"
PROPOSED_LEARNED_LOFTR_MIN_NCC="${PROPOSED_LEARNED_LOFTR_MIN_NCC:-${LEARNED_EXPORT_LOFTR_MIN_NCC:-}}"
PROPOSED_LEARNED_LOFTR_MAX_FB="${PROPOSED_LEARNED_LOFTR_MAX_FB:-${LEARNED_EXPORT_LOFTR_MAX_FB:-}}"
PROPOSED_LEARNED_MIN_CLASSICAL_AGE="${PROPOSED_LEARNED_MIN_CLASSICAL_AGE:-${LEARNED_EXPORT_MIN_CLASSICAL_AGE:-0.0}}"
PROPOSED_LEARNED_MIN_GRID_GAIN="${PROPOSED_LEARNED_MIN_GRID_GAIN:-${LEARNED_EXPORT_MIN_GRID_GAIN:-0.041}}"
PROPOSED_LEARNED_MIN_NEW_CELLS="${PROPOSED_LEARNED_MIN_NEW_CELLS:-${LEARNED_EXPORT_MIN_NEW_CELLS:-1}}"
PROPOSED_LEARNED_MIN_NEW_CELL_RATIO="${PROPOSED_LEARNED_MIN_NEW_CELL_RATIO:-${LEARNED_EXPORT_MIN_NEW_CELL_RATIO:-0.30}}"
PROPOSED_LEARNED_COVERAGE_GAIN_MAX_CLASSICAL_TRACKS="${PROPOSED_LEARNED_COVERAGE_GAIN_MAX_CLASSICAL_TRACKS:-${LEARNED_EXPORT_COVERAGE_GAIN_MAX_CLASSICAL_TRACKS:-0}}"
PROPOSED_LEARNED_LOFTR_PLANAR_RESCUE="${PROPOSED_LEARNED_LOFTR_PLANAR_RESCUE:-${LEARNED_EXPORT_LOFTR_PLANAR_RESCUE:-0}}"
PROPOSED_LEARNED_LOFTR_PLANAR_MAX_COUNT="${PROPOSED_LEARNED_LOFTR_PLANAR_MAX_COUNT:-${LEARNED_EXPORT_LOFTR_PLANAR_MAX_COUNT:-3}}"
PROPOSED_LEARNED_LOFTR_PLANAR_MAX_CLASSICAL_GRID="${PROPOSED_LEARNED_LOFTR_PLANAR_MAX_CLASSICAL_GRID:-${LEARNED_EXPORT_LOFTR_PLANAR_MAX_CLASSICAL_GRID:-0.92}}"
PROPOSED_LEARNED_LOFTR_WEAK_CELL_RESCUE="${PROPOSED_LEARNED_LOFTR_WEAK_CELL_RESCUE:-${LEARNED_EXPORT_LOFTR_WEAK_CELL_RESCUE:-0}}"
PROPOSED_LEARNED_LOFTR_WEAK_CELL_MAX_COUNT="${PROPOSED_LEARNED_LOFTR_WEAK_CELL_MAX_COUNT:-${LEARNED_EXPORT_LOFTR_WEAK_CELL_MAX_COUNT:-0}}"
PROPOSED_LEARNED_LOFTR_WEAK_CELL_MAX_OCCUPANCY="${PROPOSED_LEARNED_LOFTR_WEAK_CELL_MAX_OCCUPANCY:-${LEARNED_EXPORT_LOFTR_WEAK_CELL_MAX_OCCUPANCY:-48}}"
PROPOSED_LEARNED_WEAK_CELL_RESCUE="${PROPOSED_LEARNED_WEAK_CELL_RESCUE:-${LEARNED_EXPORT_WEAK_CELL_RESCUE:-0}}"
PROPOSED_LEARNED_WEAK_CELL_MAX_COUNT="${PROPOSED_LEARNED_WEAK_CELL_MAX_COUNT:-${LEARNED_EXPORT_WEAK_CELL_MAX_COUNT:-2}}"
PROPOSED_LEARNED_WEAK_CELL_MIN_CANDIDATES="${PROPOSED_LEARNED_WEAK_CELL_MIN_CANDIDATES:-${LEARNED_EXPORT_WEAK_CELL_MIN_CANDIDATES:-5}}"
PROPOSED_LEARNED_WEAK_CELL_MAX_OCCUPANCY="${PROPOSED_LEARNED_WEAK_CELL_MAX_OCCUPANCY:-${LEARNED_EXPORT_WEAK_CELL_MAX_OCCUPANCY:-8}}"
PROPOSED_LEARNED_WEAK_CELL_MIN_CLASSICAL_MOTION_PX="${PROPOSED_LEARNED_WEAK_CELL_MIN_CLASSICAL_MOTION_PX:-${LEARNED_EXPORT_WEAK_CELL_MIN_CLASSICAL_MOTION_PX:-3.0}}"
PROPOSED_LEARNED_WEAK_CELL_MAX_CLASSICAL_GRID="${PROPOSED_LEARNED_WEAK_CELL_MAX_CLASSICAL_GRID:-${LEARNED_EXPORT_WEAK_CELL_MAX_CLASSICAL_GRID:-0.82}}"
PROPOSED_LEARNED_WEAK_CELL_MAX_CLASSICAL_TRACKS="${PROPOSED_LEARNED_WEAK_CELL_MAX_CLASSICAL_TRACKS:-${LEARNED_EXPORT_WEAK_CELL_MAX_CLASSICAL_TRACKS:-0}}"

KLT_CONFIG="${KLT_CONFIG:-$ROOT/uw_frontend/configs/klt_frontend.yaml}"
PROPOSED_CONFIG="${PROPOSED_CONFIG:-$ROOT/uw_frontend/configs/experiments/formal_three_layer_vins_frontend.yaml}"
OUT_DIR="$ROOT/logs/slam_learning_gate_validation"
mkdir -p "$OUT_DIR"

run_h07() {
  local start="$1"
  local end="$2"
  local label="$3"
  if [[ "$RUN_BASELINE" == "1" ]]; then
    FRONTEND_CONFIG="$KLT_CONFIG" \
    PREPROCESS=adaptive_clahe \
    MEASUREMENT_SELECTION=0 \
    EXPORT_MAX_FEATURES="$BASELINE_EXPORT_MAX_FEATURES" \
    FORCE_EXPORT="$FORCE_EXPORT" \
    TAG="${VALIDATION_TAG_PREFIX}_${label}_klt" \
    PORT=11431 \
      ./scripts/run_aqualoc_real_vins_eval.sh external "$start" "$end" klt "$EVERY_N"
  fi
  if [[ "$RUN_PROTECTED_BASELINE" == "1" ]]; then
    FRONTEND_CONFIG="$PROPOSED_CONFIG" \
    PREPROCESS=adaptive_clahe \
    MEASUREMENT_SELECTION=0 \
    FORCE_EXPORT="$FORCE_EXPORT" \
    FORMAL_THREE_LAYER_EXPORT=1 \
    BACKEND_QUALITY_MODE=vins_safe \
    BACKEND_QUALITY_FLOOR="$PROTECTED_BACKEND_QUALITY_FLOOR" \
    BACKEND_QUALITY_ALPHA=0.65 \
    EXPORT_MAX_FEATURES="$PROTECTED_EXPORT_MAX_FEATURES" \
    TAG="${VALIDATION_TAG_PREFIX}_${label}_kltprotected" \
    PORT=11433 \
      ./scripts/run_aqualoc_real_vins_eval.sh external "$start" "$end" klt "$EVERY_N"
  fi
  if [[ "$RUN_PROPOSED" == "1" ]]; then
    FRONTEND_CONFIG="$PROPOSED_CONFIG" \
    PREPROCESS=adaptive_clahe \
    MEASUREMENT_SELECTION=0 \
    FORCE_EXPORT="$FORCE_EXPORT" \
    FORMAL_THREE_LAYER_EXPORT=1 \
    LEARNED_EXPORT_BENEFIT_ALL_SOURCES="$PROPOSED_BENEFIT_ALL_SOURCES" \
    LEARNED_EXPORT_MATURE_CELL_RESCUE="$PROPOSED_MATURE_CELL_RESCUE" \
    LEARNED_EXPORT_MIN_CLASSICAL_GRID="$PROPOSED_LEARNED_MIN_CLASSICAL_GRID" \
    LEARNED_EXPORT_MIN_CLASSICAL_TRACKS="$PROPOSED_LEARNED_MIN_CLASSICAL_TRACKS" \
    LEARNED_EXPORT_MIN_AGE="$PROPOSED_LEARNED_MIN_AGE" \
    LEARNED_EXPORT_MIN_NCC="$PROPOSED_LEARNED_MIN_NCC" \
    LEARNED_EXPORT_MAX_FB="$PROPOSED_LEARNED_MAX_FB" \
    LEARNED_EXPORT_LOFTR_MIN_QUALITY="$PROPOSED_LEARNED_LOFTR_MIN_QUALITY" \
    LEARNED_EXPORT_LOFTR_MIN_NCC="$PROPOSED_LEARNED_LOFTR_MIN_NCC" \
    LEARNED_EXPORT_LOFTR_MAX_FB="$PROPOSED_LEARNED_LOFTR_MAX_FB" \
    LEARNED_EXPORT_MIN_CLASSICAL_AGE="$PROPOSED_LEARNED_MIN_CLASSICAL_AGE" \
    LEARNED_EXPORT_MIN_GRID_GAIN="$PROPOSED_LEARNED_MIN_GRID_GAIN" \
    LEARNED_EXPORT_MIN_NEW_CELLS="$PROPOSED_LEARNED_MIN_NEW_CELLS" \
    LEARNED_EXPORT_MIN_NEW_CELL_RATIO="$PROPOSED_LEARNED_MIN_NEW_CELL_RATIO" \
    LEARNED_EXPORT_COVERAGE_GAIN_MAX_CLASSICAL_TRACKS="$PROPOSED_LEARNED_COVERAGE_GAIN_MAX_CLASSICAL_TRACKS" \
    LEARNED_EXPORT_LOFTR_PLANAR_RESCUE="$PROPOSED_LEARNED_LOFTR_PLANAR_RESCUE" \
    LEARNED_EXPORT_LOFTR_PLANAR_MAX_COUNT="$PROPOSED_LEARNED_LOFTR_PLANAR_MAX_COUNT" \
    LEARNED_EXPORT_LOFTR_PLANAR_MAX_CLASSICAL_GRID="$PROPOSED_LEARNED_LOFTR_PLANAR_MAX_CLASSICAL_GRID" \
    LEARNED_EXPORT_LOFTR_WEAK_CELL_RESCUE="$PROPOSED_LEARNED_LOFTR_WEAK_CELL_RESCUE" \
    LEARNED_EXPORT_LOFTR_WEAK_CELL_MAX_COUNT="$PROPOSED_LEARNED_LOFTR_WEAK_CELL_MAX_COUNT" \
    LEARNED_EXPORT_LOFTR_WEAK_CELL_MAX_OCCUPANCY="$PROPOSED_LEARNED_LOFTR_WEAK_CELL_MAX_OCCUPANCY" \
    LEARNED_EXPORT_WEAK_CELL_RESCUE="$PROPOSED_LEARNED_WEAK_CELL_RESCUE" \
    LEARNED_EXPORT_WEAK_CELL_MAX_COUNT="$PROPOSED_LEARNED_WEAK_CELL_MAX_COUNT" \
    LEARNED_EXPORT_WEAK_CELL_MIN_CANDIDATES="$PROPOSED_LEARNED_WEAK_CELL_MIN_CANDIDATES" \
    LEARNED_EXPORT_WEAK_CELL_MAX_OCCUPANCY="$PROPOSED_LEARNED_WEAK_CELL_MAX_OCCUPANCY" \
    LEARNED_EXPORT_WEAK_CELL_MIN_CLASSICAL_MOTION_PX="$PROPOSED_LEARNED_WEAK_CELL_MIN_CLASSICAL_MOTION_PX" \
    LEARNED_EXPORT_WEAK_CELL_MAX_CLASSICAL_GRID="$PROPOSED_LEARNED_WEAK_CELL_MAX_CLASSICAL_GRID" \
    LEARNED_EXPORT_WEAK_CELL_MAX_CLASSICAL_TRACKS="$PROPOSED_LEARNED_WEAK_CELL_MAX_CLASSICAL_TRACKS" \
    VINS_SAFE_MAX_TOTAL="$PROPOSED_VINS_SAFE_MAX_TOTAL" \
    VINS_SAFE_MAX_LEARNED="$PROPOSED_VINS_SAFE_MAX_LEARNED" \
    INIT_LOFTR_SIDECAR_RESCUE="$PROPOSED_INIT_LOFTR_SIDECAR_RESCUE" \
    SEMIDENSE_FALLBACK_METHOD=loftr \
    BACKEND_QUALITY_MODE=vins_safe \
    BACKEND_QUALITY_FLOOR="$PROPOSED_BACKEND_QUALITY_FLOOR" \
    BACKEND_QUALITY_ALPHA=0.65 \
    BACKEND_LOFTR_QUALITY_SCALE="$PROPOSED_BACKEND_LOFTR_QUALITY_SCALE" \
    EXPORT_MAX_FEATURES="$PROPOSED_EXPORT_MAX_FEATURES" \
    TAG="${VALIDATION_TAG_PREFIX}_${label}_proposed" \
    PORT=11432 \
      ./scripts/run_aqualoc_real_vins_eval.sh external "$start" "$end" hybrid_superpoint_lightglue "$EVERY_N"
  fi
}

run_archaeo() {
  local seq="$1"
  local start="$2"
  local end="$3"
  local label="$4"
  if [[ "$RUN_BASELINE" == "1" ]]; then
    FRONTEND_CONFIG="$KLT_CONFIG" \
    PREPROCESS=adaptive_clahe \
    MEASUREMENT_SELECTION=0 \
    EXPORT_MAX_FEATURES="$BASELINE_EXPORT_MAX_FEATURES" \
    FORCE_EXPORT="$FORCE_EXPORT" \
    TAG="${VALIDATION_TAG_PREFIX}_${label}_klt" \
    PORT=11441 \
      ./scripts/run_aqualoc_archaeo_vins_eval.sh external "$seq" "$start" "$end" klt "$EVERY_N"
  fi
  if [[ "$RUN_PROTECTED_BASELINE" == "1" ]]; then
    FRONTEND_CONFIG="$PROPOSED_CONFIG" \
    PREPROCESS=adaptive_clahe \
    MEASUREMENT_SELECTION=0 \
    FORCE_EXPORT="$FORCE_EXPORT" \
    FORMAL_THREE_LAYER_EXPORT=1 \
    BACKEND_QUALITY_MODE=vins_safe \
    BACKEND_QUALITY_FLOOR="$PROTECTED_BACKEND_QUALITY_FLOOR" \
    BACKEND_QUALITY_ALPHA=0.65 \
    EXPORT_MAX_FEATURES="$PROTECTED_EXPORT_MAX_FEATURES" \
    TAG="${VALIDATION_TAG_PREFIX}_${label}_kltprotected" \
    PORT=11443 \
      ./scripts/run_aqualoc_archaeo_vins_eval.sh external "$seq" "$start" "$end" klt "$EVERY_N"
  fi
  if [[ "$RUN_PROPOSED" == "1" ]]; then
    FRONTEND_CONFIG="$PROPOSED_CONFIG" \
    PREPROCESS=adaptive_clahe \
    MEASUREMENT_SELECTION=0 \
    FORCE_EXPORT="$FORCE_EXPORT" \
    FORMAL_THREE_LAYER_EXPORT=1 \
    LEARNED_EXPORT_BENEFIT_ALL_SOURCES="$PROPOSED_BENEFIT_ALL_SOURCES" \
    LEARNED_EXPORT_MATURE_CELL_RESCUE="$PROPOSED_MATURE_CELL_RESCUE" \
    LEARNED_EXPORT_MIN_CLASSICAL_GRID="$PROPOSED_LEARNED_MIN_CLASSICAL_GRID" \
    LEARNED_EXPORT_MIN_CLASSICAL_TRACKS="$PROPOSED_LEARNED_MIN_CLASSICAL_TRACKS" \
    LEARNED_EXPORT_MIN_AGE="$PROPOSED_LEARNED_MIN_AGE" \
    LEARNED_EXPORT_MIN_NCC="$PROPOSED_LEARNED_MIN_NCC" \
    LEARNED_EXPORT_MAX_FB="$PROPOSED_LEARNED_MAX_FB" \
    LEARNED_EXPORT_LOFTR_MIN_QUALITY="$PROPOSED_LEARNED_LOFTR_MIN_QUALITY" \
    LEARNED_EXPORT_LOFTR_MIN_NCC="$PROPOSED_LEARNED_LOFTR_MIN_NCC" \
    LEARNED_EXPORT_LOFTR_MAX_FB="$PROPOSED_LEARNED_LOFTR_MAX_FB" \
    LEARNED_EXPORT_MIN_CLASSICAL_AGE="$PROPOSED_LEARNED_MIN_CLASSICAL_AGE" \
    LEARNED_EXPORT_MIN_GRID_GAIN="$PROPOSED_LEARNED_MIN_GRID_GAIN" \
    LEARNED_EXPORT_MIN_NEW_CELLS="$PROPOSED_LEARNED_MIN_NEW_CELLS" \
    LEARNED_EXPORT_MIN_NEW_CELL_RATIO="$PROPOSED_LEARNED_MIN_NEW_CELL_RATIO" \
    LEARNED_EXPORT_COVERAGE_GAIN_MAX_CLASSICAL_TRACKS="$PROPOSED_LEARNED_COVERAGE_GAIN_MAX_CLASSICAL_TRACKS" \
    LEARNED_EXPORT_LOFTR_PLANAR_RESCUE="$PROPOSED_LEARNED_LOFTR_PLANAR_RESCUE" \
    LEARNED_EXPORT_LOFTR_PLANAR_MAX_COUNT="$PROPOSED_LEARNED_LOFTR_PLANAR_MAX_COUNT" \
    LEARNED_EXPORT_LOFTR_PLANAR_MAX_CLASSICAL_GRID="$PROPOSED_LEARNED_LOFTR_PLANAR_MAX_CLASSICAL_GRID" \
    LEARNED_EXPORT_LOFTR_WEAK_CELL_RESCUE="$PROPOSED_LEARNED_LOFTR_WEAK_CELL_RESCUE" \
    LEARNED_EXPORT_LOFTR_WEAK_CELL_MAX_COUNT="$PROPOSED_LEARNED_LOFTR_WEAK_CELL_MAX_COUNT" \
    LEARNED_EXPORT_LOFTR_WEAK_CELL_MAX_OCCUPANCY="$PROPOSED_LEARNED_LOFTR_WEAK_CELL_MAX_OCCUPANCY" \
    LEARNED_EXPORT_WEAK_CELL_RESCUE="$PROPOSED_LEARNED_WEAK_CELL_RESCUE" \
    LEARNED_EXPORT_WEAK_CELL_MAX_COUNT="$PROPOSED_LEARNED_WEAK_CELL_MAX_COUNT" \
    LEARNED_EXPORT_WEAK_CELL_MIN_CANDIDATES="$PROPOSED_LEARNED_WEAK_CELL_MIN_CANDIDATES" \
    LEARNED_EXPORT_WEAK_CELL_MAX_OCCUPANCY="$PROPOSED_LEARNED_WEAK_CELL_MAX_OCCUPANCY" \
    LEARNED_EXPORT_WEAK_CELL_MIN_CLASSICAL_MOTION_PX="$PROPOSED_LEARNED_WEAK_CELL_MIN_CLASSICAL_MOTION_PX" \
    LEARNED_EXPORT_WEAK_CELL_MAX_CLASSICAL_GRID="$PROPOSED_LEARNED_WEAK_CELL_MAX_CLASSICAL_GRID" \
    LEARNED_EXPORT_WEAK_CELL_MAX_CLASSICAL_TRACKS="$PROPOSED_LEARNED_WEAK_CELL_MAX_CLASSICAL_TRACKS" \
    VINS_SAFE_MAX_TOTAL="$PROPOSED_VINS_SAFE_MAX_TOTAL" \
    VINS_SAFE_MAX_LEARNED="$PROPOSED_VINS_SAFE_MAX_LEARNED" \
    INIT_LOFTR_SIDECAR_RESCUE="$PROPOSED_INIT_LOFTR_SIDECAR_RESCUE" \
    SEMIDENSE_FALLBACK_METHOD=loftr \
    BACKEND_QUALITY_MODE=vins_safe \
    BACKEND_QUALITY_FLOOR="$PROPOSED_BACKEND_QUALITY_FLOOR" \
    BACKEND_QUALITY_ALPHA=0.65 \
    BACKEND_LOFTR_QUALITY_SCALE="$PROPOSED_BACKEND_LOFTR_QUALITY_SCALE" \
    EXPORT_MAX_FEATURES="$PROPOSED_EXPORT_MAX_FEATURES" \
    TAG="${VALIDATION_TAG_PREFIX}_${label}_proposed" \
    PORT=11442 \
      ./scripts/run_aqualoc_archaeo_vins_eval.sh external "$seq" "$start" "$end" hybrid_superpoint_lightglue "$EVERY_N"
  fi
}

for window in $WINDOWS; do
  case "$window" in
    h07_normal)
      run_h07 1660 1950 h07_1660_1950
      ;;
    a06_lowtexture)
      run_archaeo 6 2100 2550 a06_2100_2550
      ;;
    a06_short_lowtexture)
      run_archaeo 6 2280 2360 a06_2280_2360
      ;;
    a05_normal)
      run_archaeo 5 2800 3300 a05_2800_3300
      ;;
    a08_lowtexture)
      run_archaeo 8 4520 4680 a08_4520_4680
      ;;
    a08_long_lowtexture)
      run_archaeo 8 4480 4680 a08_4480_4680
      ;;
    a09_lowtexture)
      run_archaeo 9 5800 6200 a09_5800_6200
      ;;
    *)
      echo "unknown window: $window" >&2
      exit 2
      ;;
  esac
done

python3 scripts/summarize_vins_trajectory_runs.py \
  --runs-root logs/aqualoc_real_vins \
  --output-csv "$OUT_DIR/h07_runs_summary.csv"
python3 scripts/summarize_vins_trajectory_runs.py \
  --runs-root logs/aqualoc_archaeo_vins \
  --output-csv "$OUT_DIR/archaeo_runs_summary.csv"
python3 scripts/summarize_learning_gate_validation.py \
  --tag-prefix "$VALIDATION_TAG_PREFIX" \
  --output-dir "$OUT_DIR"
