#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-/home/ma/AQUA-FE_WS}"
cd "$ROOT"

EVERY_N="${EVERY_N:-2}"
RUN_VINS="${RUN_VINS:-0}"
FORCE_EXPORT="${FORCE_EXPORT:-1}"
FORCE_RAW="${FORCE_RAW:-1}"
PREPARE_BAG="${PREPARE_BAG:-1}"
TAG_PREFIX="${TAG_PREFIX:-may29_active_xfeat}"

COMMON_ENV=(
  OMP_NUM_THREADS=2
  MKL_NUM_THREADS=2
  OPENBLAS_NUM_THREADS=2
  RUN_VINS="$RUN_VINS"
  FORCE_EXPORT="$FORCE_EXPORT"
  FORCE_RAW="$FORCE_RAW"
  PREPARE_BAG="$PREPARE_BAG"
  RAW_BAG="$ROOT/datasets/full_downloads/afrl_hf/ros1_bags/cemetery.bag"
  GT_TXT="$ROOT/datasets/full_downloads/afrl_hf/colmap_groundtruth/cemetery.txt"
  CAMCHAIN="$ROOT/datasets/full_downloads/afrl_hf/camera_imu_parameters/camchain_cemetery.yaml"
  CAMERA_KEY=cam1
  SRC_IMAGE_TOPIC=/cam_fr/image_raw/compressed
  IMAGE_SCALE=0.5
  FRONTEND_CONFIG="$ROOT/uw_frontend/configs/experiments/paper_vins_safe_learned_sidecar.yaml"
  SEMIDENSE_FALLBACK_METHOD=none
  PREPROCESS=adaptive_clahe
  BACKEND_QUALITY_FLOOR=none
  BACKEND_XFEAT_QUALITY_SCALE="${BACKEND_XFEAT_QUALITY_SCALE:-0.40}"
  FORMAL_THREE_LAYER_EXPORT=1
  FORMAL_EXPORT_ADAPTIVE_MIRROR_FALLBACK=1
  FORMAL_EXPORT_ALLOW_SPARSE_BACKBONE=1
  FORMAL_EXPORT_LOW_TEXTURE_ACTIVE_SIDECAR=1
  EXPORT_CLASSICAL_MIRROR_BACKBONE=1
  PRESERVE_SIDECARS_THROUGH_SELECTION=1
  EXPORT_MAX_FEATURES=180
  MEASUREMENT_SELECTION_MAX_FEATURES=180
  VINS_SAFE_MAX_TOTAL=180
  VINS_SAFE_WARMUP_FRAMES=20
  VINS_SAFE_MAX_LEARNED=18
  VINS_SAFE_MIN_LEARNED_AGE=1
  VINS_INIT_KLT_ONLY_FRAMES=20
  LOW_PARALLAX_LEARNED_HOLDOFF_FRAMES=0
  LEARNED_EXPORT_BENEFIT_ALL_SOURCES=1
  LEARNED_EXPORT_MIN_CLASSICAL_TRACKS=300
  LEARNED_EXPORT_MIN_CLASSICAL_GRID=0.78
  LEARNED_EXPORT_MIN_AGE=1
  LEARNED_EXPORT_MIN_QUALITY=0.05
  LEARNED_EXPORT_MIN_NCC=0.35
  LEARNED_EXPORT_MAX_FB=1.50
  LEARNED_EXPORT_MIN_GRID_GAIN=0.0
  LEARNED_EXPORT_MIN_NEW_CELLS=1
  LEARNED_EXPORT_MIN_NEW_CELL_RATIO=0.05
  LEARNED_EXPORT_MAX_PER_NEW_CELL=2
  LEARNED_EXPORT_MIN_CLASSICAL_MOTION_PX=0.0
  LEARNED_EXPORT_COVERAGE_GAIN_MAX_CLASSICAL_TRACKS=0
  LEARNED_EXPORT_WEAK_CELL_RESCUE=1
  LEARNED_EXPORT_NON_LOFTR_WEAK_CELL_RESCUE=1
  LEARNED_EXPORT_WEAK_CELL_MAX_COUNT=10
  LEARNED_EXPORT_WEAK_CELL_MIN_CANDIDATES=2
  LEARNED_EXPORT_WEAK_CELL_MAX_OCCUPANCY=12
  LEARNED_EXPORT_WEAK_CELL_MIN_CLASSICAL_MOTION_PX=0.0
  LEARNED_EXPORT_WEAK_CELL_MAX_CLASSICAL_GRID=0.82
  LEARNED_EXPORT_WEAK_CELL_MAX_CLASSICAL_TRACKS=0
  LEARNED_EXPORT_VISIBLE_TRACK_GATE=1
  LEARNED_EXPORT_VISIBLE_TRACK_MIN_FRAMES=1
  LEARNED_EXPORT_VISIBLE_TRACK_MAX_GAP=2
  LEARNED_EXPORT_FRESH_CONFIRMATION_HOLD_FRAMES=4
)

run_window() {
  local start="$1"
  local duration="$2"
  local label="$3"
  env "${COMMON_ENV[@]}" \
    TAG="${TAG_PREFIX}_${label}_export" \
    bash scripts/run_afrl_cave_vins_eval.sh external hybrid_xfeat "$start" "$duration" "$EVERY_N"
}

run_window 25 20 fr25_45
run_window 70 30 fr70_100

python3 scripts/summarize_run_evidence.py \
  --runs \
  "logs/afrl_cave_v31/external_hybrid_xfeat_every${EVERY_N}_${TAG_PREFIX}_fr25_45_export" \
  "logs/afrl_cave_v31/external_hybrid_xfeat_every${EVERY_N}_${TAG_PREFIX}_fr70_100_export" \
  --output-csv "logs/${TAG_PREFIX}_export_summary.csv"
